server:
  servlet:
    context-path: /authority
  port: 9999

# 驱动配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    druid:
      #数据库链接
      url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=CTT
      #帐号
      username: root
      #密码
      password: root
      #Driver
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化大小
      initial-size: 5
      # 配置5,当线程池数量不足，自动补充
      min-idle: 5
      #最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #检测数据库链接是否有效，必须配置
      validation-query: SELECT 1 FROM DUAL
      #此项配置为true即可，不影响性能，并且保证安全性。意义为：申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #获取链接的时候，不校验是否可用，开启会有损性能
      test-on-borrow: false
      #归还链接到连接池的时候校验链接是否可用。
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true


#引入日志打印文件
logging:
  config: classpath:logback.xml
